---
# biological parameters
mu: 1.84e-10


# should we leave the alignments already completed in the alignments
# directory alone?
resume_alignment: False

HMM_symbols:
    match: '+'
    mismatch: '-'
    unknown: '?'
    unsequenced: 'n'
    gap: '-'
    unaligned: '?'
    masked: 'x'

output_root: /tigress/tcomi/aclark4_temp/results
input_root: /tigress/AKEY/akey_vol2/aclark4/nobackup

paths:
    # optional log file
    # log_file: introgression.log
    fasta_suffix: .fa  # suffix for _all_ fasta files
    # suffix for _all_ alignment files
    # this needs to match the suffix output by mugsy
    alignment_suffix: .maf

    masks: /tigress/tcomi/aclark4_temp/par4/masked/
    alignments: /tigress/tcomi/aclark4_temp/par4/

    test_strains:
        - "__INPUT_ROOT__/100_genomes/genomes_gb/\
           {strain}_chr{chrom}.fa"

    simulations:
        sim_base: __OUTPUT_ROOT__/sim
        prefix: sim_out_
        suffix: .txt

    analysis:
        analysis_base: __OUTPUT_ROOT__/analysisp4e2
        regions: __ANALYSIS_BASE__/regions/{state}.fa.gz
        region_index: __ANALYSIS_BASE__/regions/{state}.pkl
        genes: __ANALYSIS_BASE__/genes/
        blocks: __ANALYSIS_BASE__/blocks_{state}_p4e2.txt
        labeled_blocks: "__ANALYSIS_BASE__/blocks_{state}_p4e2_labeled.txt"
        quality: __ANALYSIS_BASE__/block_{state}_quality.txt
        hmm_initial: __ANALYSIS_BASE__/hmm_initial.txt
        hmm_trained: __ANALYSIS_BASE__/hmm_trained.txt
        probabilities: __ANALYSIS_BASE__/probabilities.txt.gz
        alignment: __ALIGNMENTS__/{prefix}_{strain}_chr{chrom}_mafft.maf
        positions: __ANALYSIS_BASE__/positions.txt.gz
        masked_intervals: __MASKS__/{strain}_chr{chrom}_intervals.txt

    # software install locations
    software:
        root_install: /tigress/anneec/software
        mugsy: __ROOT_INSTALL__/mugsy/
        tcoffee: "__ROOT_INSTALL__/\
            T-COFFEE_installer_Version_11.00.8cbe486_linux_x64/bin/"
        mafft: __ROOT_INSTALL__/mafft/bin/
        ms: __ROOT_INSTALL__/msdir/
        # including dustmasker
        blast: "__ROOT_INSTALL__/ncbi-blast-2.7.1+-src/\
            c++/ReleaseMT/bin/"
        orffinder: __ROOT_INSTALL__/
        ldselect: __ROOT_INSTALL__/ldSelect/
        structure: __ROOT_INSTALL__/structure/

# chromosomes: ['I']
chromosomes: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII',
              'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI']

# can optionally list all strains to consider
# if blank will glob with TEST_STRAINS paths
# strains:

# can provide a prefix for the alignment files
# if blank will be the reference and known state names joined with '_'

analysis_params:
    tag: p2e4
    convergence_threshold: 0.001
    # threshold can be 'viterbi' or a float to threshold probabilities
    threshold: viterbi
    input_root: /tigress/AKEY/akey_vol2/aclark4/nobackup

    # master known state, prepeded to list of known states
    # TODO need to use the other name for S288c!
    reference:
        name: S288c
        base_dir: __INPUT_ROOT__/100_genomes/genomes/S288c_SGD-R64/
        gene_bank_dir: __INPUT_ROOT__/S288c/
        interval_name: S288c_SGD-R64  # if different than name

    known_states:
        - name: CBS432
          base_dir: /tigress/anneec/projects/introgression/data/CBS432/
          gene_bank_dir: __INPUT_ROOT__/CBS432/
          expected_length: 10000
          expected_fraction: 0.025

        - name: N_45
          base_dir: __INPUT_ROOT__/para_sgrp/strains/N_45/
          gene_bank_dir: null
          expected_length: 10000
          expected_fraction: 0.025

        - name: DBVPG6304
          base_dir: __INPUT_ROOT__/para_sgrp/strains/DBVPG6304/
          gene_bank_dir: null
          expected_length: 10000
          expected_fraction: 0.025

        - name: UWOPS91_917_1
          base_dir: __INPUT_ROOT__/para_sgrp/strains/UWOPS91_917_1/
          gene_bank_dir: null
          expected_length: 10000
          expected_fraction: 0.025

    unknown_states:
        - name: unknown
          expected_length: 1000
          expected_fraction: 0.01

    gene_bank_all: __INPUT_ROOT__/100_genomes/sequence.gb
